Claim:
    type: entity
    table: claim
    indexes:
        fk_claim_client1_idx:
            columns:
                - client_idclient
    id:
        idclaim:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        claimdate:
            type: datetime
            nullable: true
        object:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    oneToOne:
        clientclient:
            targetEntity: Client
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_idclient:
                    referencedColumnName: idclient
            orphanRemoval: false
    lifecycleCallbacks: {  }
