Client:
    type: entity
    table: client
    uniqueConstraints:
        cin_UNIQUE:
            columns:
                - cin
    id:
        idclient:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        lastname:
            type: integer
            nullable: false
            options:
                unsigned: false
        cin:
            type: integer
            nullable: false
            options:
                unsigned: false
        address:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        tel:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        clientavatar:
            type: blob
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
