Event:
    type: entity
    table: event
    id:
        idevent:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        startdate:
            type: datetime
            nullable: true
        enddate:
            type: datetime
            nullable: true
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        title:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
