Product:
    type: entity
    table: product
    id:
        idproduct:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        productname:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        price:
            type: float
            nullable: true
            precision: 10
            scale: 0
        category:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        productimage:
            type: blob
            nullable: true
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
