back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /admin

heaven:
    resource: "@HeavenBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: '@AppBundle/Controller/'
    type: annotation
