<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6pihpzo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6pihpzo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6pihpzo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6pihpzo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6pihpzo\appDevDebugProjectContainer([
    'container.build_hash' => '6pihpzo',
    'container.build_id' => '6b70fe24',
    'container.build_time' => 1549642878,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6pihpzo');
